FROM node:lts-alpine AS builder

WORKDIR /usr/src/app

COPY ./api/package*.json ./

RUN npm install

COPY ./api .

RUN npm run build

FROM node:lts

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package*.json ./

EXPOSE 3000

CMD ["npm", "run", "start:prod:migrate"]
